require("config")

if dimoresenable == true then
--Changes
require("prototypes.ores.changes")
--Pumpjack
require("prototypes.ores.pump-2")
require("prototypes.ores.pump-3")
--Mining
require("prototypes.ores.mining-range-1")
require("prototypes.ores.mining-range-2")
require("prototypes.ores.mining-range-3")
require("prototypes.ores.mining-speed-1")
require("prototypes.ores.mining-speed-2")
require("prototypes.ores.mining-speed-3")
--Technology
require("prototypes.ores.tech")
else
--Changes
require("prototypes.normal.changes")
--Pumpjack
require("prototypes.normal.pump-2")
require("prototypes.normal.pump-3")
--Mining
require("prototypes.normal.mining-range-1")
require("prototypes.normal.mining-range-2")
require("prototypes.normal.mining-range-3")
require("prototypes.normal.mining-speed-1")
require("prototypes.normal.mining-speed-2")
require("prototypes.normal.mining-speed-3")
--Technology
require("prototypes.normal.tech")
end