data:extend(
{
	{
		type="item",
		name="rop-circuit",
		icon="__RAGE-Ore-Processing__/graphics/ropc.png",
		flags={"goes-to-main-inventory"},
		subgroup="rage-rop3",
		order="a",
		stack_size=50
	},
	{
		type="item",
		name="rop1",
		icon="__RAGE-Ore-Processing__/graphics/rop1.png",
		flags={"goes-to-main-inventory"},
		subgroup="rage-rop3",
		order="b",
		place_result="rop1m",
		stack_size=20
	},
	{
		type="item",
		name="rop2",
		icon="__RAGE-Ore-Processing__/graphics/rop2.png",
		flags={"goes-to-main-inventory"},
		subgroup="rage-rop3",
		order="c",
		place_result="rop2m",
		stack_size=20
	},
	{
		type="item",
		name="pureiron",
		icon="__RAGE-Ore-Processing__/graphics/pure-iron.png",
		flags={"goes-to-main-inventory"},
		subgroup="rage-rop1",
		stack_size=50
	},
	{
		type="item",
		name="atomiron",
		icon="__RAGE-Ore-Processing__/graphics/atom-iron.png",
		flags={"goes-to-main-inventory"},
		subgroup="rage-rop2",
		stack_size=50
	},
	{
		type="item",
		name="purecopper",
		icon="__RAGE-Ore-Processing__/graphics/pure-copper.png",
		flags={"goes-to-main-inventory"},
		subgroup="rage-rop1",
		stack_size=50
	},
	{
		type="item",
		name="atomcopper",
		icon="__RAGE-Ore-Processing__/graphics/atom-copper.png",
		flags={"goes-to-main-inventory"},
		subgroup="rage-rop2",
		stack_size=50
	},
	{
		type="item",
		name="mmatter",
		icon="__RAGE-Ore-Processing__/graphics/mmatter.png",
		flags={"goes-to-main-inventory"},
		subgroup="rage-rop2",
		stack_size=50
	}
}
)	