data:extend(
{
	{
		type="assembling-machine",
		name="rop1m",
		icon="__RAGE-Ore-Processing__/graphics/rop1.png",
		flags={"placeable-neutral", "placeable-player", "player-creation"},
		minable={hardness=0.2,mining_time=0.5,result="rop1"},
		max_health=250,
		corpse="big-remnants",
		dying_explosion="medium-explosion",
		resistances=
		{
			{
				type="fire",
				percent=70
			}
		},
		collision_box={{-1.2,-1.2},{1.2,1.2}},
		selection_box={{-1.5,-1.5},{1.5,1.5}},
		fast_replaceable_group="rage-ropm",
		animation=
		{
			filename="__RAGE-Ore-Processing__/graphics/rage-ore-processor.png",
			priority="high",
			width=113,
			height=99,
			frame_count=32,
			line_length=8,
			shift={0.4,-0.06},
		},
		open_sound={filename="__base__/sound/machine-open.ogg",volume=0.85},
		close_sound={filename="__base__/sound/machine-close.ogg",volume=0.75},
		vehicle_impact_sound={filename="__base__/sound/car-metal-impact.ogg",volume=0.65},
		working_sound=
		{
			sound=
			{
				{
					filename="__base__/sound/assembling-machine-t2-1.ogg",
					volume=0.8
				},
				{
					filename="__base__/sound/assembling-machine-t2-2.ogg",
					volume=0.8
				},
			},
			idle_sound={filename="__base__/sound/idle1.ogg",volume=0.6},
			apparent_volume=1.5,
		},
		crafting_categories={"rage-ropc"},
		crafting_speed=1.0,
		energy_source=
		{
			type="electric",
			usage_priority="secondary-input",
			emissions=0.04/2.5
		},
		energy_usage="150kW",
		ingredient_count=2,
		module_specification=
		{
			module_slots=0
		},
		allowed_effects={"consumption","speed","productivity","pollution"}
	},
	{
		type="assembling-machine",
		name="rop2m",
		icon="__RAGE-Ore-Processing__/graphics/rop2.png",
		flags={"placeable-neutral", "placeable-player", "player-creation"},
		minable={hardness=0.2,mining_time=0.5,result="rop2"},
		max_health=300,
		corpse="big-remnants",
		dying_explosion="medium-explosion",
		resistances=
		{
			{
				type="fire",
				percent=70
			}
		},
		collision_box={{-1.2,-1.2},{1.2,1.2}},
		selection_box={{-1.5,-1.5},{1.5,1.5}},
		fast_replaceable_group="rage-ropm",
		animation=
		{
			filename="__RAGE-Ore-Processing__/graphics/rage-ore-processor-2.png",
			priority="high",
			width=142,
			height=113,
			frame_count=32,
			line_length=8,
			shift={0.84,-0.09},
		},
		open_sound={filename="__base__/sound/machine-open.ogg",volume=0.85},
		close_sound={filename="__base__/sound/machine-close.ogg",volume=0.75},
		vehicle_impact_sound={filename="__base__/sound/car-metal-impact.ogg",volume=0.65},
		working_sound=
		{
			sound=
			{
				{
					filename="__base__/sound/assembling-machine-t2-1.ogg",
					volume=0.8
				},
				{
					filename="__base__/sound/assembling-machine-t2-2.ogg",
					volume=0.8
				},
			},
			idle_sound={filename="__base__/sound/idle1.ogg",volume=0.6},
			apparent_volume=1.5,
		},
		crafting_categories={"rage-ropc"},
		crafting_speed=2.0,
		energy_source=
		{
			type="electric",
			usage_priority="secondary-input",
			emissions=0.03/3.5
		},
		energy_usage="210kW",
		ingredient_count=2,
		module_specification=
		{
			module_slots=2
		},
		allowed_effects={"consumption","speed","productivity","pollution"}
	}
}
)
			
		