data:extend(
{
	{
		type="recipe",
		name="rop-pure-iron-plate",
		enabled=false,
		category="smelting",
		energy_required=3,
		ingredients={{"pureiron",1}},
		icon="__RAGE-Ore-Processing__/graphics/iron-plate.png",
		subgroup="rage-rop1",
		order="a-a",
		results={{"iron-plate",1}}
	},
	{
		type="recipe",
		name="rop-pure-copper-plate",
		enabled=false,
		category="smelting",
		energy_required=3,
		ingredients={{"purecopper",1}},
		icon="__RAGE-Ore-Processing__/graphics/copper-plate.png",
		subgroup="rage-rop1",
		order="a-b",
		results={{"copper-plate",1}}
	},
	{
		type="recipe",
		name="rop-pure-iron-1",
		enabled=false,
		category="rage-ropc",
		energy_required=9,
		ingredients={{"iron-ore",4}},
		icon="__RAGE-Ore-Processing__/graphics/pure-iron-o.png",
		subgroup="rage-rop1",
		order="b-a",
		results=
		{
			{"pureiron",4},
			{"stone",1}
		}
	},
	{
		type="recipe",
		name="rop-pure-copper-1",
		enabled=false,
		category="rage-ropc",
		energy_required=9,
		ingredients={{"copper-ore",4}},
		icon="__RAGE-Ore-Processing__/graphics/pure-copper-o.png",
		subgroup="rage-rop1",
		order="b-c",
		results=
		{
			{"purecopper",4},
			{"stone",1}
		}
	},
	{
		type="recipe",
		name="rop-pure-iron-2",
		enabled=false,
		category="rage-ropc",
		energy_required=3,
		ingredients={{"atomiron",1}},
		icon="__RAGE-Ore-Processing__/graphics/pure-iron-a.png",
		subgroup="rage-rop2",
		order="b-b",
		results={{"pureiron",1}}
	},
	{
		type="recipe",
		name="rop-pure-copper-2",
		enabled=false,
		category="rage-ropc",
		energy_required=3,
		ingredients={{"atomcopper",1}},
		icon="__RAGE-Ore-Processing__/graphics/pure-copper-a.png",
		subgroup="rage-rop2",
		order="b-d",
		results={{"purecopper",1}}
	},
	{
		type="recipe",
		name="rop-atom-iron-1",
		enabled=false,
		category="rage-ropc",
		energy_required=4.5,
		ingredients={{"pureiron",1}},
		icon="__RAGE-Ore-Processing__/graphics/atom-iron-o.png",
		subgroup="rage-rop2",
		order="b-e",
		results={{"atomiron",1}}
	},
	{
		type="recipe",
		name="rop-atom-copper-1",
		enabled=false,
		category="rage-ropc",
		energy_required=4.5,
		ingredients={{"purecopper",1}},
		icon="__RAGE-Ore-Processing__/graphics/atom-copper-o.png",
		subgroup="rage-rop2",
		order="b-g",
		results={{"atomcopper",1}}
	},
	{
		type="recipe",
		name="rop-atom-iron-2",
		enabled=false,
		category="rage-ropc",
		energy_required=9,
		ingredients=
		{
			{"atomiron",2},
			{"mmatter",1}
		},
		icon="__RAGE-Ore-Processing__/graphics/atom-iron-m.png",
		subgroup="rage-rop2",
		order="b-f",
		results={{"atomiron",3}}
	},
	{
		type="recipe",
		name="rop-atom-copper-2",
		enabled=false,
		category="rage-ropc",
		energy_required=9,
		ingredients=
		{
			{"atomcopper",2},
			{"mmatter",1}
		},
		icon="__RAGE-Ore-Processing__/graphics/atom-copper-m.png",
		subgroup="rage-rop2",
		order="b-h",
		results={{"atomcopper",3}}
	},
	{
		type="recipe",
		name="rop-mmatter",
		enabled=false,
		category="rage-ropc",
		energy_required=90,
		ingredients=
		{
			{"alien-artifact",1},
			{"stone",10}
		},
		order="b-i",
		result="mmatter",
		result_count=10
	},
	{
		type="recipe",
		name="rop-ropc",
		enabled=false,
		category="advanced-crafting",
		energy_required=30,
		ingredients=
		{
			{"productivity-module",2},
			{"advanced-circuit",10}
		},
		order="c-a",
		result="rop-circuit",
	},
	{
		type="recipe",
		name="rop1mr",
		enabled=false,
		category="advanced-crafting",
		energy_required=10,
		ingredients=
		{
			{"assembling-machine-2",1},
			{"speed-module",2},
			{"rop-circuit",1}
		},
		order="c-b",
		result="rop1"
	},
	{
		type="recipe",
		name="rop2mr",
		enabled=false,
		category="advanced-crafting",
		energy_required=10,
		ingredients=
		{
			{"rop1",1},
			{"speed-module-2",2}
		},
		order="c-c",
		result="rop2"
	},
}
)		