data:extend(
{
	{
		type="technology",
		name="rop-t1",
		icon="__RAGE-Ore-Processing__/graphics/ropc.png",
		effects=
		{
			{type="unlock-recipe",recipe="rop-pure-iron-plate"},
			{type="unlock-recipe",recipe="rop-pure-copper-plate"},
			{type="unlock-recipe",recipe="rop-pure-iron-1"},
			{type="unlock-recipe",recipe="rop-pure-copper-1"},
			{type="unlock-recipe",recipe="rop-ropc"},
			{type="unlock-recipe",recipe="rop1mr"}
		},
		prerequisites={"advanced-material-processing-2","productivity-module"},
		unit=
		{
			count=250,
			ingredients=
			{
				{"science-pack-1",2},
				{"science-pack-2",1},
				{"science-pack-3",1}
			},
			time=30
		},
		order="r-a-a"
	},
	{
		type="technology",
		name="rop-t2",
		icon="__RAGE-Ore-Processing__/graphics/mmatter.png",
		effects=
		{
			{type="unlock-recipe",recipe="rop-pure-iron-2"},
			{type="unlock-recipe",recipe="rop-pure-copper-2"},
			{type="unlock-recipe",recipe="rop-atom-iron-1"},
			{type="unlock-recipe",recipe="rop-atom-copper-1"},
			{type="unlock-recipe",recipe="rop-atom-iron-2"},
			{type="unlock-recipe",recipe="rop-atom-copper-2"},
			{type="unlock-recipe",recipe="rop-mmatter"}
		},
		prerequisites={"rop-t1","alien-technology"},
		unit=
		{
			count=500,
			ingredients=
			{
				{"science-pack-1",2},
				{"science-pack-2",1},
				{"science-pack-3",1},
				{"alien-science-pack",2}
			},
			time=30
		},
		order="r-a-b"
	},
	{
		type="technology",
		name="rop-t3",
		icon="__RAGE-Ore-Processing__/graphics/rop2.png",
		effects=
		{
			{type="unlock-recipe",recipe="rop2mr"}
		},
		prerequisites={"rop-t2","productivity-module-2"},
		unit=
		{
			count=500,
			ingredients=
			{
				{"science-pack-1",1},
				{"science-pack-2",1},
				{"science-pack-3",1},
				{"alien-science-pack",1}
			},
			time=30
		},
		order="r-a-c"
	}
}
)