require("config")

if dimoresenable == true then
--Changes
require("prototypes.ores.changes")
--Speed
require("prototypes.ores.speed-4")
require("prototypes.ores.speed-5")
--Productivity
require("prototypes.ores.productivity-4")
require("prototypes.ores.productivity-5")
--Effectivity
require("prototypes.ores.effectivity-4")
require("prototypes.ores.effectivity-5")
--Pollution
require("prototypes.ores.pollution-1")
require("prototypes.ores.pollution-2")
require("prototypes.ores.pollution-3")
require("prototypes.ores.pollution-4")
require("prototypes.ores.pollution-5")
--Mix MK4
require("prototypes.ores.speed-effectivity-4")
require("prototypes.ores.speed-productivity-4")
require("prototypes.ores.speed-pollution-4")
require("prototypes.ores.pollution-effectivity-4")
require("prototypes.ores.pollution-productivity-4")
require("prototypes.ores.effectivity-productivity-4")
--Mix MK5
require("prototypes.ores.speed-effectivity-5")
require("prototypes.ores.speed-productivity-5")
require("prototypes.ores.speed-pollution-5")
require("prototypes.ores.pollution-effectivity-5")
require("prototypes.ores.pollution-productivity-5")
require("prototypes.ores.effectivity-productivity-5")
--Welder
require("prototypes.ores.recipe-category")
require("prototypes.ores.welder")
--Tech
require("prototypes.ores.tech")
else
--Changes
require("prototypes.normal.changes")
--Speed
require("prototypes.normal.speed-4")
require("prototypes.normal.speed-5")
--Productivity
require("prototypes.normal.productivity-4")
require("prototypes.normal.productivity-5")
--Effectivity
require("prototypes.normal.effectivity-4")
require("prototypes.normal.effectivity-5")
--Pollution
require("prototypes.normal.pollution-1")
require("prototypes.normal.pollution-2")
require("prototypes.normal.pollution-3")
require("prototypes.normal.pollution-4")
require("prototypes.normal.pollution-5")
--Mix MK4
require("prototypes.normal.speed-effectivity-4")
require("prototypes.normal.speed-productivity-4")
require("prototypes.normal.speed-pollution-4")
require("prototypes.normal.pollution-effectivity-4")
require("prototypes.normal.pollution-productivity-4")
require("prototypes.normal.effectivity-productivity-4")
--Mix MK5
require("prototypes.normal.speed-effectivity-5")
require("prototypes.normal.speed-productivity-5")
require("prototypes.normal.speed-pollution-5")
require("prototypes.normal.pollution-effectivity-5")
require("prototypes.normal.pollution-productivity-5")
require("prototypes.normal.effectivity-productivity-5")
--Welder
require("prototypes.normal.recipe-category")
require("prototypes.normal.welder")
--Tech
require("prototypes.normal.tech")
end